package poultryinspector;

import ccre.chan.BooleanInputProducer;
import ccre.chan.BooleanOutput;
import ccre.chan.BooleanStatus;
import ccre.chan.FloatInputProducer;
import ccre.chan.FloatOutput;
import ccre.chan.FloatStatus;
import ccre.cluck.CluckGlobals;
import ccre.event.Event;
import ccre.event.EventConsumer;
import ccre.event.EventSource;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 * A form that provides some debugging tools to debug cluck networks. More
 * debugging tools should be added here as they are created.
 *
 * @author skeggsc
 */
public class DebugToolsForm extends javax.swing.JFrame {

    public DebugToolsForm() {
        initComponents();
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                setVisible(false);
                dispose();
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        txtOutput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEventConnect = new javax.swing.JButton();
        btnEventCreate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnFloatCreate = new javax.swing.JButton();
        btnFloatConnect = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnBooleanConnect = new javax.swing.JButton();
        btnCreateBoolean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setLabelFor(txtInput);
        jLabel1.setText("Input/Source Name");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setLabelFor(txtOutput);
        jLabel2.setText("Output/Consumer Name");

        btnEventConnect.setText("Connect Events");
        btnEventConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventConnectActionPerformed(evt);
            }
        });

        btnEventCreate.setText("Create Events");
        btnEventCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEventConnect)
                    .addComponent(btnEventCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnEventCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEventConnect))
        );

        btnFloatCreate.setText("Create Floats");
        btnFloatCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloatCreateActionPerformed(evt);
            }
        });

        btnFloatConnect.setText("Connect Floats");
        btnFloatConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloatConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFloatCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFloatConnect))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnFloatCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFloatConnect))
        );

        btnBooleanConnect.setText("Connect Booleans");
        btnBooleanConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBooleanConnectActionPerformed(evt);
            }
        });

        btnCreateBoolean.setText("Create Booleans");
        btnCreateBoolean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBooleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBooleanConnect)
            .addComponent(btnCreateBoolean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnCreateBoolean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBooleanConnect))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInput)
                    .addComponent(txtOutput)))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEventConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventConnectActionPerformed
        String in = txtInput.getText(), out = txtOutput.getText();
        if (out.isEmpty() || in.isEmpty()) {
            return;
        }
        EventConsumer cnsm = CluckGlobals.encoder.subscribeEventConsumer(out);
        EventSource src = CluckGlobals.encoder.subscribeEventSource(in);
        src.addListener(cnsm);
    }//GEN-LAST:event_btnEventConnectActionPerformed

    private void btnBooleanConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBooleanConnectActionPerformed
        String in = txtInput.getText(), out = txtOutput.getText();
        if (out.isEmpty() || in.isEmpty()) {
            return;
        }
        BooleanOutput cnsm = CluckGlobals.encoder.subscribeBooleanOutput(out);
        BooleanInputProducer src = CluckGlobals.encoder.subscribeBooleanInputProducer(in, false);
        src.addTarget(cnsm);
    }//GEN-LAST:event_btnBooleanConnectActionPerformed

    private void btnFloatConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloatConnectActionPerformed
        String in = txtInput.getText(), out = txtOutput.getText();
        if (out.isEmpty() || in.isEmpty()) {
            return;
        }
        FloatOutput cnsm = CluckGlobals.encoder.subscribeFloatOutput(out);
        FloatInputProducer src = CluckGlobals.encoder.subscribeFloatInputProducer(in, 0);
        src.addTarget(cnsm);
    }//GEN-LAST:event_btnFloatConnectActionPerformed

    private void btnEventCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventCreateActionPerformed
        String in = txtInput.getText(), out = txtOutput.getText();
        if (out.isEmpty() || in.isEmpty()) {
            return;
        }
        Event e = new Event();
        CluckGlobals.encoder.publishEventConsumer(out, e);
        CluckGlobals.encoder.publishEventSource(in, e);
    }//GEN-LAST:event_btnEventCreateActionPerformed

    private void btnCreateBooleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBooleanActionPerformed
        String in = txtInput.getText(), out = txtOutput.getText();
        if (out.isEmpty() || in.isEmpty()) {
            return;
        }
        BooleanStatus b = new BooleanStatus();
        CluckGlobals.encoder.publishBooleanOutput(out, b);
        CluckGlobals.encoder.publishBooleanInputProducer(in, b);
    }//GEN-LAST:event_btnCreateBooleanActionPerformed

    private void btnFloatCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloatCreateActionPerformed
        String in = txtInput.getText(), out = txtOutput.getText();
        if (out.isEmpty() || in.isEmpty()) {
            return;
        }
        FloatStatus b = new FloatStatus();
        CluckGlobals.encoder.publishFloatOutput(out, b);
        CluckGlobals.encoder.publishFloatInputProducer(in, b);
    }//GEN-LAST:event_btnFloatCreateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooleanConnect;
    private javax.swing.JButton btnCreateBoolean;
    private javax.swing.JButton btnEventConnect;
    private javax.swing.JButton btnEventCreate;
    private javax.swing.JButton btnFloatConnect;
    private javax.swing.JButton btnFloatCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
