/*
 * Copyright 2013 Colby Skeggs
 * 
 * This file is part of the CCRE, the Common Chicken Runtime Engine.
 * 
 * The CCRE is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 * 
 * The CCRE is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with the CCRE.  If not, see <http://www.gnu.org/licenses/>.
 */
package ccre.igneous;

import ccre.chan.BooleanInputPoll;
import ccre.chan.BooleanOutput;
import ccre.chan.FloatInputPoll;
import ccre.chan.FloatOutput;
import ccre.event.EventSource;
import ccre.log.LogLevel;
import ccre.log.Logger;
import java.awt.Color;
import java.awt.EventQueue;
import java.util.HashMap;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JSlider;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class EmulatorForm extends javax.swing.JFrame {

    static {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            Logger.info("Set look-and-feel!");
        } catch (ClassNotFoundException ex) {
            Logger.log(LogLevel.WARNING, "Cannot use look-and-feel!", ex);
        } catch (InstantiationException ex) {
            Logger.log(LogLevel.WARNING, "Cannot use look-and-feel!", ex);
        } catch (IllegalAccessException ex) {
            Logger.log(LogLevel.WARNING, "Cannot use look-and-feel!", ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.log(LogLevel.WARNING, "Cannot use look-and-feel!", ex);
        }
    }

    public EmulatorForm() {
        initComponents();
        joy1 = new EmuJoystick(new javax.swing.JToggleButton[]{btnJoy1_1, btnJoy1_2, btnJoy1_3, btnJoy1_4, btnJoy1_5, btnJoy1_6, btnJoy1_7, btnJoy1_8, btnJoy1_9, btnJoy1_10, btnJoy1_11, btnJoy1_12}, new javax.swing.JSlider[]{sliJoy1_1, sliJoy1_2, sliJoy1_3, sliJoy1_4, sliJoy1_5, sliJoy1_6});
        joy2 = new EmuJoystick(new javax.swing.JToggleButton[]{btnJoy2_1, btnJoy2_2, btnJoy2_3, btnJoy2_4, btnJoy2_5, btnJoy2_6, btnJoy2_7, btnJoy2_8, btnJoy2_9, btnJoy2_10, btnJoy2_11, btnJoy2_12}, new javax.swing.JSlider[]{sliJoy2_1, sliJoy2_2, sliJoy2_3, sliJoy2_4, sliJoy2_5, sliJoy2_6});
        joy3 = new EmuJoystick(new javax.swing.JToggleButton[]{btnJoy3_1, btnJoy3_2, btnJoy3_3, btnJoy3_4, btnJoy3_5, btnJoy3_6, btnJoy3_7, btnJoy3_8, btnJoy3_9, btnJoy3_10, btnJoy3_11, btnJoy3_12}, new javax.swing.JSlider[]{sliJoy3_1, sliJoy3_2, sliJoy3_3, sliJoy3_4, sliJoy3_5, sliJoy3_6});
        joy4 = new EmuJoystick(new javax.swing.JToggleButton[]{btnJoy4_1, btnJoy4_2, btnJoy4_3, btnJoy4_4, btnJoy4_5, btnJoy4_6, btnJoy4_7, btnJoy4_8, btnJoy4_9, btnJoy4_10, btnJoy4_11, btnJoy4_12}, new javax.swing.JSlider[]{sliJoy4_1, sliJoy4_2, sliJoy4_3, sliJoy4_4, sliJoy4_5, sliJoy4_6});
        motors = new JProgressBar[]{motor1, motor2, motor3, motor4, motor5, motor6, motor7, motor8, motor9, motor10};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpMode = new javax.swing.ButtonGroup();
        radTele = new javax.swing.JRadioButton();
        radAuto = new javax.swing.JRadioButton();
        radTest = new javax.swing.JRadioButton();
        btnEnable = new javax.swing.JToggleButton();
        labStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnJoy1_8 = new javax.swing.JToggleButton();
        btnJoy1_6 = new javax.swing.JToggleButton();
        btnJoy1_4 = new javax.swing.JToggleButton();
        btnJoy1_7 = new javax.swing.JToggleButton();
        btnJoy1_5 = new javax.swing.JToggleButton();
        btnJoy1_1 = new javax.swing.JToggleButton();
        btnJoy1_2 = new javax.swing.JToggleButton();
        btnJoy1_3 = new javax.swing.JToggleButton();
        btnJoy1_9 = new javax.swing.JToggleButton();
        btnJoy1_10 = new javax.swing.JToggleButton();
        btnJoy1_12 = new javax.swing.JToggleButton();
        btnJoy1_11 = new javax.swing.JToggleButton();
        sliJoy1_1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        sliJoy1_4 = new javax.swing.JSlider();
        sliJoy1_5 = new javax.swing.JSlider();
        sliJoy1_2 = new javax.swing.JSlider();
        sliJoy1_3 = new javax.swing.JSlider();
        sliJoy1_6 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        btnJoy2_8 = new javax.swing.JToggleButton();
        btnJoy2_7 = new javax.swing.JToggleButton();
        btnJoy2_2 = new javax.swing.JToggleButton();
        btnJoy2_4 = new javax.swing.JToggleButton();
        btnJoy2_1 = new javax.swing.JToggleButton();
        btnJoy2_3 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        sliJoy2_2 = new javax.swing.JSlider();
        sliJoy2_3 = new javax.swing.JSlider();
        sliJoy2_4 = new javax.swing.JSlider();
        sliJoy2_1 = new javax.swing.JSlider();
        btnJoy2_6 = new javax.swing.JToggleButton();
        btnJoy2_5 = new javax.swing.JToggleButton();
        btnJoy2_11 = new javax.swing.JToggleButton();
        btnJoy2_12 = new javax.swing.JToggleButton();
        btnJoy2_9 = new javax.swing.JToggleButton();
        btnJoy2_10 = new javax.swing.JToggleButton();
        sliJoy2_5 = new javax.swing.JSlider();
        sliJoy2_6 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        btnJoy3_12 = new javax.swing.JToggleButton();
        btnJoy3_11 = new javax.swing.JToggleButton();
        btnJoy3_10 = new javax.swing.JToggleButton();
        btnJoy3_9 = new javax.swing.JToggleButton();
        btnJoy3_8 = new javax.swing.JToggleButton();
        btnJoy3_7 = new javax.swing.JToggleButton();
        btnJoy3_5 = new javax.swing.JToggleButton();
        btnJoy3_6 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        sliJoy3_5 = new javax.swing.JSlider();
        sliJoy3_6 = new javax.swing.JSlider();
        sliJoy3_3 = new javax.swing.JSlider();
        sliJoy3_4 = new javax.swing.JSlider();
        sliJoy3_1 = new javax.swing.JSlider();
        sliJoy3_2 = new javax.swing.JSlider();
        btnJoy3_4 = new javax.swing.JToggleButton();
        btnJoy3_3 = new javax.swing.JToggleButton();
        btnJoy3_2 = new javax.swing.JToggleButton();
        btnJoy3_1 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        sliJoy4_6 = new javax.swing.JSlider();
        sliJoy4_5 = new javax.swing.JSlider();
        sliJoy4_4 = new javax.swing.JSlider();
        sliJoy4_3 = new javax.swing.JSlider();
        sliJoy4_2 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        sliJoy4_1 = new javax.swing.JSlider();
        btnJoy4_1 = new javax.swing.JToggleButton();
        btnJoy4_3 = new javax.swing.JToggleButton();
        btnJoy4_7 = new javax.swing.JToggleButton();
        btnJoy4_8 = new javax.swing.JToggleButton();
        btnJoy4_6 = new javax.swing.JToggleButton();
        btnJoy4_5 = new javax.swing.JToggleButton();
        btnJoy4_4 = new javax.swing.JToggleButton();
        btnJoy4_2 = new javax.swing.JToggleButton();
        btnJoy4_11 = new javax.swing.JToggleButton();
        btnJoy4_12 = new javax.swing.JToggleButton();
        btnJoy4_9 = new javax.swing.JToggleButton();
        btnJoy4_10 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        motor2 = new javax.swing.JProgressBar();
        motor3 = new javax.swing.JProgressBar();
        motor1 = new javax.swing.JProgressBar();
        motor5 = new javax.swing.JProgressBar();
        motor4 = new javax.swing.JProgressBar();
        motor6 = new javax.swing.JProgressBar();
        motor7 = new javax.swing.JProgressBar();
        motor8 = new javax.swing.JProgressBar();
        motor9 = new javax.swing.JProgressBar();
        motor10 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sol1 = new javax.swing.JLabel();
        sol2 = new javax.swing.JLabel();
        sol3 = new javax.swing.JLabel();
        sol5 = new javax.swing.JLabel();
        sol4 = new javax.swing.JLabel();
        sol7 = new javax.swing.JLabel();
        sol6 = new javax.swing.JLabel();
        sol8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        analog1 = new javax.swing.JSlider();
        analog2 = new javax.swing.JSlider();
        analog3 = new javax.swing.JSlider();
        analog4 = new javax.swing.JSlider();
        analog5 = new javax.swing.JSlider();
        analog6 = new javax.swing.JSlider();
        analog7 = new javax.swing.JSlider();
        analog8 = new javax.swing.JSlider();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        digital1 = new javax.swing.JToggleButton();
        digital2 = new javax.swing.JToggleButton();
        digital3 = new javax.swing.JToggleButton();
        digital4 = new javax.swing.JToggleButton();
        digital5 = new javax.swing.JToggleButton();
        digital6 = new javax.swing.JToggleButton();
        digital7 = new javax.swing.JToggleButton();
        digital8 = new javax.swing.JToggleButton();
        digital9 = new javax.swing.JToggleButton();
        digital10 = new javax.swing.JToggleButton();
        digital11 = new javax.swing.JToggleButton();
        digital12 = new javax.swing.JToggleButton();
        digital13 = new javax.swing.JToggleButton();
        digital14 = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lcd1 = new javax.swing.JLabel();
        lcd2 = new javax.swing.JLabel();
        lcd3 = new javax.swing.JLabel();
        lcd4 = new javax.swing.JLabel();
        lcd5 = new javax.swing.JLabel();
        lcd6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labCompressor = new javax.swing.JLabel();
        btnAddEncoder = new javax.swing.JButton();
        encoderSelect = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGrpMode.add(radTele);
        radTele.setSelected(true);
        radTele.setText("Teleoperated");

        btnGrpMode.add(radAuto);
        radAuto.setText("Autonomous");

        btnGrpMode.add(radTest);
        radTest.setText("Testing");

        btnEnable.setText("Enable");
        btnEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableActionPerformed(evt);
            }
        });

        labStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labStatus.setText("Disabled");

        btnJoy1_8.setText("8");
        btnJoy1_8.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_6.setText("6");
        btnJoy1_6.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_4.setText("4");
        btnJoy1_4.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_7.setText("7");
        btnJoy1_7.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_5.setText("5");
        btnJoy1_5.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_1.setText("1");
        btnJoy1_1.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_2.setText("2");
        btnJoy1_2.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_3.setText("3");
        btnJoy1_3.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_9.setText("9");
        btnJoy1_9.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy1_10.setText("10");
        btnJoy1_10.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy1_12.setText("12");
        btnJoy1_12.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy1_11.setText("11");
        btnJoy1_11.setMargin(new java.awt.Insets(2, 4, 2, 4));

        sliJoy1_1.setMaximum(10);
        sliJoy1_1.setMinimum(-10);
        sliJoy1_1.setMinorTickSpacing(1);
        sliJoy1_1.setSnapToTicks(true);
        sliJoy1_1.setValue(0);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Joystick 1");

        sliJoy1_4.setMaximum(10);
        sliJoy1_4.setMinimum(-10);
        sliJoy1_4.setMinorTickSpacing(1);
        sliJoy1_4.setSnapToTicks(true);
        sliJoy1_4.setValue(0);

        sliJoy1_5.setMaximum(10);
        sliJoy1_5.setMinimum(-10);
        sliJoy1_5.setMinorTickSpacing(1);
        sliJoy1_5.setSnapToTicks(true);
        sliJoy1_5.setValue(0);

        sliJoy1_2.setMaximum(10);
        sliJoy1_2.setMinimum(-10);
        sliJoy1_2.setMinorTickSpacing(1);
        sliJoy1_2.setSnapToTicks(true);
        sliJoy1_2.setValue(0);

        sliJoy1_3.setMaximum(10);
        sliJoy1_3.setMinimum(-10);
        sliJoy1_3.setMinorTickSpacing(1);
        sliJoy1_3.setSnapToTicks(true);
        sliJoy1_3.setValue(0);

        sliJoy1_6.setMaximum(10);
        sliJoy1_6.setMinimum(-10);
        sliJoy1_6.setMinorTickSpacing(1);
        sliJoy1_6.setSnapToTicks(true);
        sliJoy1_6.setValue(0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(sliJoy1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addComponent(sliJoy1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(sliJoy1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(sliJoy1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(sliJoy1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnJoy1_7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy1_8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy1_9))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnJoy1_10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy1_11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy1_12))
            .addComponent(sliJoy1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnJoy1_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy1_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy1_6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnJoy1_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy1_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy1_3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(sliJoy1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy1_1)
                    .addComponent(btnJoy1_2)
                    .addComponent(btnJoy1_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy1_4)
                    .addComponent(btnJoy1_5)
                    .addComponent(btnJoy1_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy1_8)
                    .addComponent(btnJoy1_9)
                    .addComponent(btnJoy1_7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy1_10)
                    .addComponent(btnJoy1_11)
                    .addComponent(btnJoy1_12)))
        );

        btnJoy2_8.setText("8");
        btnJoy2_8.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy2_7.setText("7");
        btnJoy2_7.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy2_2.setText("2");
        btnJoy2_2.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy2_4.setText("4");
        btnJoy2_4.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy2_1.setText("1");
        btnJoy2_1.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy2_3.setText("3");
        btnJoy2_3.setMargin(new java.awt.Insets(2, 7, 2, 7));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Joystick 2");

        sliJoy2_2.setMaximum(10);
        sliJoy2_2.setMinimum(-10);
        sliJoy2_2.setMinorTickSpacing(1);
        sliJoy2_2.setSnapToTicks(true);
        sliJoy2_2.setValue(0);

        sliJoy2_3.setMaximum(10);
        sliJoy2_3.setMinimum(-10);
        sliJoy2_3.setMinorTickSpacing(1);
        sliJoy2_3.setSnapToTicks(true);
        sliJoy2_3.setValue(0);

        sliJoy2_4.setMaximum(10);
        sliJoy2_4.setMinimum(-10);
        sliJoy2_4.setMinorTickSpacing(1);
        sliJoy2_4.setSnapToTicks(true);
        sliJoy2_4.setValue(0);

        sliJoy2_1.setMaximum(10);
        sliJoy2_1.setMinimum(-10);
        sliJoy2_1.setMinorTickSpacing(1);
        sliJoy2_1.setSnapToTicks(true);
        sliJoy2_1.setValue(0);

        btnJoy2_6.setText("6");
        btnJoy2_6.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy2_5.setText("5");
        btnJoy2_5.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy2_11.setText("11");
        btnJoy2_11.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy2_12.setText("12");
        btnJoy2_12.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy2_9.setText("9");
        btnJoy2_9.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy2_10.setText("10");
        btnJoy2_10.setMargin(new java.awt.Insets(2, 4, 2, 4));

        sliJoy2_5.setMaximum(10);
        sliJoy2_5.setMinimum(-10);
        sliJoy2_5.setMinorTickSpacing(1);
        sliJoy2_5.setSnapToTicks(true);
        sliJoy2_5.setValue(0);

        sliJoy2_6.setMaximum(10);
        sliJoy2_6.setMinimum(-10);
        sliJoy2_6.setMinorTickSpacing(1);
        sliJoy2_6.setSnapToTicks(true);
        sliJoy2_6.setValue(0);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnJoy2_7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy2_8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy2_9))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnJoy2_10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy2_11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy2_12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnJoy2_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy2_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy2_3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnJoy2_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy2_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy2_6))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliJoy2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sliJoy2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliJoy2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sliJoy2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sliJoy2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sliJoy2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(sliJoy2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy2_1)
                    .addComponent(btnJoy2_2)
                    .addComponent(btnJoy2_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy2_4)
                    .addComponent(btnJoy2_5)
                    .addComponent(btnJoy2_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy2_8)
                    .addComponent(btnJoy2_9)
                    .addComponent(btnJoy2_7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy2_10)
                    .addComponent(btnJoy2_11)
                    .addComponent(btnJoy2_12)))
        );

        btnJoy3_12.setText("12");
        btnJoy3_12.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy3_11.setText("11");
        btnJoy3_11.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy3_10.setText("10");
        btnJoy3_10.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy3_9.setText("9");
        btnJoy3_9.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy3_8.setText("8");
        btnJoy3_8.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy3_7.setText("7");
        btnJoy3_7.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy3_5.setText("5");
        btnJoy3_5.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy3_6.setText("6");
        btnJoy3_6.setMargin(new java.awt.Insets(2, 7, 2, 7));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Joystick 3");

        sliJoy3_5.setMaximum(10);
        sliJoy3_5.setMinimum(-10);
        sliJoy3_5.setMinorTickSpacing(1);
        sliJoy3_5.setSnapToTicks(true);
        sliJoy3_5.setValue(0);

        sliJoy3_6.setMaximum(10);
        sliJoy3_6.setMinimum(-10);
        sliJoy3_6.setMinorTickSpacing(1);
        sliJoy3_6.setSnapToTicks(true);
        sliJoy3_6.setValue(0);

        sliJoy3_3.setMaximum(10);
        sliJoy3_3.setMinimum(-10);
        sliJoy3_3.setMinorTickSpacing(1);
        sliJoy3_3.setSnapToTicks(true);
        sliJoy3_3.setValue(0);

        sliJoy3_4.setMaximum(10);
        sliJoy3_4.setMinimum(-10);
        sliJoy3_4.setMinorTickSpacing(1);
        sliJoy3_4.setSnapToTicks(true);
        sliJoy3_4.setValue(0);

        sliJoy3_1.setMaximum(10);
        sliJoy3_1.setMinimum(-10);
        sliJoy3_1.setMinorTickSpacing(1);
        sliJoy3_1.setSnapToTicks(true);
        sliJoy3_1.setValue(0);

        sliJoy3_2.setMaximum(10);
        sliJoy3_2.setMinimum(-10);
        sliJoy3_2.setMinorTickSpacing(1);
        sliJoy3_2.setSnapToTicks(true);
        sliJoy3_2.setValue(0);

        btnJoy3_4.setText("4");
        btnJoy3_4.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy3_3.setText("3");
        btnJoy3_3.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy3_2.setText("2");
        btnJoy3_2.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy3_1.setText("1");
        btnJoy3_1.setMargin(new java.awt.Insets(2, 7, 2, 7));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliJoy3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sliJoy3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sliJoy3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sliJoy3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sliJoy3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(sliJoy3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnJoy3_7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy3_8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy3_9))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnJoy3_10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy3_11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy3_12))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnJoy3_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy3_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy3_3))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnJoy3_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy3_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoy3_6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(sliJoy3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy3_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy3_1)
                    .addComponent(btnJoy3_2)
                    .addComponent(btnJoy3_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy3_4)
                    .addComponent(btnJoy3_5)
                    .addComponent(btnJoy3_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy3_8)
                    .addComponent(btnJoy3_9)
                    .addComponent(btnJoy3_7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy3_10)
                    .addComponent(btnJoy3_11)
                    .addComponent(btnJoy3_12)))
        );

        sliJoy4_6.setMaximum(10);
        sliJoy4_6.setMinimum(-10);
        sliJoy4_6.setMinorTickSpacing(1);
        sliJoy4_6.setSnapToTicks(true);
        sliJoy4_6.setValue(0);

        sliJoy4_5.setMaximum(10);
        sliJoy4_5.setMinimum(-10);
        sliJoy4_5.setMinorTickSpacing(1);
        sliJoy4_5.setSnapToTicks(true);
        sliJoy4_5.setValue(0);

        sliJoy4_4.setMaximum(10);
        sliJoy4_4.setMinimum(-10);
        sliJoy4_4.setMinorTickSpacing(1);
        sliJoy4_4.setSnapToTicks(true);
        sliJoy4_4.setValue(0);

        sliJoy4_3.setMaximum(10);
        sliJoy4_3.setMinimum(-10);
        sliJoy4_3.setMinorTickSpacing(1);
        sliJoy4_3.setSnapToTicks(true);
        sliJoy4_3.setValue(0);

        sliJoy4_2.setMaximum(10);
        sliJoy4_2.setMinimum(-10);
        sliJoy4_2.setMinorTickSpacing(1);
        sliJoy4_2.setSnapToTicks(true);
        sliJoy4_2.setValue(0);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Joystick 4");

        sliJoy4_1.setMaximum(10);
        sliJoy4_1.setMinimum(-10);
        sliJoy4_1.setMinorTickSpacing(1);
        sliJoy4_1.setSnapToTicks(true);
        sliJoy4_1.setValue(0);

        btnJoy4_1.setText("1");
        btnJoy4_1.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_3.setText("3");
        btnJoy4_3.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_7.setText("7");
        btnJoy4_7.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_8.setText("8");
        btnJoy4_8.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_6.setText("6");
        btnJoy4_6.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_5.setText("5");
        btnJoy4_5.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_4.setText("4");
        btnJoy4_4.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_2.setText("2");
        btnJoy4_2.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_11.setText("11");
        btnJoy4_11.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy4_12.setText("12");
        btnJoy4_12.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnJoy4_9.setText("9");
        btnJoy4_9.setMargin(new java.awt.Insets(2, 7, 2, 7));

        btnJoy4_10.setText("10");
        btnJoy4_10.setMargin(new java.awt.Insets(2, 4, 2, 4));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliJoy4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliJoy4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnJoy4_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoy4_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoy4_3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnJoy4_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoy4_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoy4_6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnJoy4_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoy4_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoy4_9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnJoy4_10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoy4_11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoy4_12))
                    .addComponent(sliJoy4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliJoy4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliJoy4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliJoy4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliJoy4_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy4_1)
                    .addComponent(btnJoy4_2)
                    .addComponent(btnJoy4_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy4_4)
                    .addComponent(btnJoy4_5)
                    .addComponent(btnJoy4_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy4_8)
                    .addComponent(btnJoy4_9)
                    .addComponent(btnJoy4_7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoy4_10)
                    .addComponent(btnJoy4_11)
                    .addComponent(btnJoy4_12)))
        );

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Motors");

        motor2.setForeground(new java.awt.Color(0, 0, 0));
        motor2.setMinimum(-100);
        motor2.setString("");
        motor2.setStringPainted(true);

        motor3.setForeground(new java.awt.Color(0, 0, 0));
        motor3.setMinimum(-100);
        motor3.setString("");
        motor3.setStringPainted(true);

        motor1.setForeground(new java.awt.Color(0, 0, 0));
        motor1.setMinimum(-100);
        motor1.setString("");
        motor1.setStringPainted(true);

        motor5.setForeground(new java.awt.Color(0, 0, 0));
        motor5.setMinimum(-100);
        motor5.setString("");
        motor5.setStringPainted(true);

        motor4.setForeground(new java.awt.Color(0, 0, 0));
        motor4.setMinimum(-100);
        motor4.setString("");
        motor4.setStringPainted(true);

        motor6.setForeground(new java.awt.Color(0, 0, 0));
        motor6.setMinimum(-100);
        motor6.setString("");
        motor6.setStringPainted(true);

        motor7.setForeground(new java.awt.Color(0, 0, 0));
        motor7.setMinimum(-100);
        motor7.setString("");
        motor7.setStringPainted(true);

        motor8.setForeground(new java.awt.Color(0, 0, 0));
        motor8.setMinimum(-100);
        motor8.setString("");
        motor8.setStringPainted(true);

        motor9.setForeground(new java.awt.Color(0, 0, 0));
        motor9.setMinimum(-100);
        motor9.setString("");
        motor9.setStringPainted(true);

        motor10.setForeground(new java.awt.Color(0, 0, 0));
        motor10.setMinimum(-100);
        motor10.setString("");
        motor10.setStringPainted(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(motor4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(motor10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Solenoids");

        sol1.setForeground(new java.awt.Color(100, 100, 100));
        sol1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sol1.setText("Solenoid 1");

        sol2.setForeground(new java.awt.Color(100, 100, 100));
        sol2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sol2.setText("Solenoid 2");

        sol3.setForeground(new java.awt.Color(100, 100, 100));
        sol3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sol3.setText("Solenoid 3");
        sol3.setToolTipText("");

        sol5.setForeground(new java.awt.Color(100, 100, 100));
        sol5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sol5.setText("Solenoid 5");
        sol5.setToolTipText("");

        sol4.setForeground(new java.awt.Color(100, 100, 100));
        sol4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sol4.setText("Solenoid 4");
        sol4.setToolTipText("");

        sol7.setForeground(new java.awt.Color(100, 100, 100));
        sol7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sol7.setText("Solenoid 7");
        sol7.setToolTipText("");

        sol6.setForeground(new java.awt.Color(100, 100, 100));
        sol6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sol6.setText("Solenoid 6");
        sol6.setToolTipText("");

        sol8.setForeground(new java.awt.Color(100, 100, 100));
        sol8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sol8.setText("Solenoid 8");
        sol8.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sol1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sol2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sol3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sol5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sol6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sol7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sol8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sol4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol8))
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Analog Inputs");

        analog1.setMaximum(4095);
        analog1.setSnapToTicks(true);
        analog1.setValue(2048);

        analog2.setMaximum(4095);
        analog2.setSnapToTicks(true);
        analog2.setValue(2048);

        analog3.setMaximum(4095);
        analog3.setSnapToTicks(true);
        analog3.setValue(2048);

        analog4.setMaximum(4095);
        analog4.setSnapToTicks(true);
        analog4.setValue(2048);

        analog5.setMaximum(4095);
        analog5.setSnapToTicks(true);
        analog5.setValue(2048);

        analog6.setMaximum(4095);
        analog6.setSnapToTicks(true);
        analog6.setValue(2048);

        analog7.setMaximum(4095);
        analog7.setSnapToTicks(true);
        analog7.setValue(2048);

        analog8.setMaximum(4095);
        analog8.setSnapToTicks(true);
        analog8.setValue(2048);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(analog1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(analog2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(analog3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(analog4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(analog5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(analog6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(analog7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(analog8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analog1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analog2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analog3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analog4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analog5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analog6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analog7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analog8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Digital Inputs");

        digital1.setText("1");
        digital1.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital2.setText("2");
        digital2.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital3.setText("3");
        digital3.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital4.setText("4");
        digital4.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital5.setText("5");
        digital5.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital6.setText("6");
        digital6.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital7.setText("7");
        digital7.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital8.setText("8");
        digital8.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital9.setText("9");
        digital9.setMargin(new java.awt.Insets(2, 7, 2, 7));

        digital10.setText("10");
        digital10.setMargin(new java.awt.Insets(2, 4, 2, 4));

        digital11.setText("11");
        digital11.setMargin(new java.awt.Insets(2, 4, 2, 4));

        digital12.setText("12");
        digital12.setMargin(new java.awt.Insets(2, 4, 2, 4));

        digital13.setText("13");
        digital13.setMargin(new java.awt.Insets(2, 4, 2, 4));

        digital14.setText("14");
        digital14.setMargin(new java.awt.Insets(2, 4, 2, 4));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(digital1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digital2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digital3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digital4))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(digital5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digital6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digital7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digital8))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(digital9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(digital13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(digital14))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(digital10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(digital11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(digital12))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(digital1)
                    .addComponent(digital2)
                    .addComponent(digital3)
                    .addComponent(digital4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(digital5)
                    .addComponent(digital6)
                    .addComponent(digital7)
                    .addComponent(digital8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(digital9)
                    .addComponent(digital10)
                    .addComponent(digital11)
                    .addComponent(digital12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(digital13)
                    .addComponent(digital14)))
        );

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DSLCD");

        lcd1.setText("-no data-");

        lcd2.setText("-no data-");

        lcd3.setText("-no data-");

        lcd4.setText("-no data-");

        lcd5.setText("-no data-");

        lcd6.setText("-no data-");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lcd1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(lcd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lcd3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lcd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lcd5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lcd6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcd2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcd3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcd4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcd5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcd6))
        );

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Compressor");

        labCompressor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCompressor.setText("NOT CONTROLLED");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labCompressor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labCompressor))
        );

        btnAddEncoder.setText("Add Encoder");
        btnAddEncoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEncoderActionPerformed(evt);
            }
        });

        encoderSelect.setModel(availableEncoderSelection);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radTele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddEncoder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encoderSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(radTele)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radTest, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(encoderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAddEncoder))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableActionPerformed
        boolean on = btnEnable.isSelected();
        radAuto.setEnabled(!on);
        radTele.setEnabled(!on);
        radTest.setEnabled(!on);
        if (on) {
            ButtonModel selection = btnGrpMode.getSelection();
            if (selection == radAuto.getModel()) {
                labStatus.setText("Autonomous");
            } else if (selection == radTele.getModel()) {
                labStatus.setText("Teleoperated");
            } else if (selection == radTest.getModel()) {
                labStatus.setText("Testing");
            } else {
                labStatus.setText("Unknown");
            }
        } else {
            labStatus.setText("Disabled");
        }
    }//GEN-LAST:event_btnEnableActionPerformed

    public FloatInputPoll makeEncoder(int aChannel, int bChannel, boolean reverse, EventSource resetWhen) {
        String name = aChannel + "::" + bChannel;
        if (reverse) {
            name += "::reverse";
        }
        availableEncoderSelection.addElement(name);
        EncoderForm enc = new EncoderForm(name);
        encoders.put(name, enc);
        return enc;
    }

    private void btnAddEncoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEncoderActionPerformed
        String s = (String) availableEncoderSelection.getSelectedItem();
        if (s == null) {
            return;
        }
        encoders.get(s).setVisible(true);
    }//GEN-LAST:event_btnAddEncoderActionPerformed

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EmulatorForm().setVisible(true);
            }
        });
    }
    public EmuJoystick joy1, joy2, joy3, joy4;
    private DefaultComboBoxModel availableEncoderSelection = new DefaultComboBoxModel();
    private HashMap<String, EncoderForm> encoders = new HashMap<String, EncoderForm>();
    private JProgressBar[] motors;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider analog1;
    private javax.swing.JSlider analog2;
    private javax.swing.JSlider analog3;
    private javax.swing.JSlider analog4;
    private javax.swing.JSlider analog5;
    private javax.swing.JSlider analog6;
    private javax.swing.JSlider analog7;
    private javax.swing.JSlider analog8;
    private javax.swing.JButton btnAddEncoder;
    private javax.swing.JToggleButton btnEnable;
    private javax.swing.ButtonGroup btnGrpMode;
    private javax.swing.JToggleButton btnJoy1_1;
    private javax.swing.JToggleButton btnJoy1_10;
    private javax.swing.JToggleButton btnJoy1_11;
    private javax.swing.JToggleButton btnJoy1_12;
    private javax.swing.JToggleButton btnJoy1_2;
    private javax.swing.JToggleButton btnJoy1_3;
    private javax.swing.JToggleButton btnJoy1_4;
    private javax.swing.JToggleButton btnJoy1_5;
    private javax.swing.JToggleButton btnJoy1_6;
    private javax.swing.JToggleButton btnJoy1_7;
    private javax.swing.JToggleButton btnJoy1_8;
    private javax.swing.JToggleButton btnJoy1_9;
    private javax.swing.JToggleButton btnJoy2_1;
    private javax.swing.JToggleButton btnJoy2_10;
    private javax.swing.JToggleButton btnJoy2_11;
    private javax.swing.JToggleButton btnJoy2_12;
    private javax.swing.JToggleButton btnJoy2_2;
    private javax.swing.JToggleButton btnJoy2_3;
    private javax.swing.JToggleButton btnJoy2_4;
    private javax.swing.JToggleButton btnJoy2_5;
    private javax.swing.JToggleButton btnJoy2_6;
    private javax.swing.JToggleButton btnJoy2_7;
    private javax.swing.JToggleButton btnJoy2_8;
    private javax.swing.JToggleButton btnJoy2_9;
    private javax.swing.JToggleButton btnJoy3_1;
    private javax.swing.JToggleButton btnJoy3_10;
    private javax.swing.JToggleButton btnJoy3_11;
    private javax.swing.JToggleButton btnJoy3_12;
    private javax.swing.JToggleButton btnJoy3_2;
    private javax.swing.JToggleButton btnJoy3_3;
    private javax.swing.JToggleButton btnJoy3_4;
    private javax.swing.JToggleButton btnJoy3_5;
    private javax.swing.JToggleButton btnJoy3_6;
    private javax.swing.JToggleButton btnJoy3_7;
    private javax.swing.JToggleButton btnJoy3_8;
    private javax.swing.JToggleButton btnJoy3_9;
    private javax.swing.JToggleButton btnJoy4_1;
    private javax.swing.JToggleButton btnJoy4_10;
    private javax.swing.JToggleButton btnJoy4_11;
    private javax.swing.JToggleButton btnJoy4_12;
    private javax.swing.JToggleButton btnJoy4_2;
    private javax.swing.JToggleButton btnJoy4_3;
    private javax.swing.JToggleButton btnJoy4_4;
    private javax.swing.JToggleButton btnJoy4_5;
    private javax.swing.JToggleButton btnJoy4_6;
    private javax.swing.JToggleButton btnJoy4_7;
    private javax.swing.JToggleButton btnJoy4_8;
    private javax.swing.JToggleButton btnJoy4_9;
    private javax.swing.JToggleButton digital1;
    private javax.swing.JToggleButton digital10;
    private javax.swing.JToggleButton digital11;
    private javax.swing.JToggleButton digital12;
    private javax.swing.JToggleButton digital13;
    private javax.swing.JToggleButton digital14;
    private javax.swing.JToggleButton digital2;
    private javax.swing.JToggleButton digital3;
    private javax.swing.JToggleButton digital4;
    private javax.swing.JToggleButton digital5;
    private javax.swing.JToggleButton digital6;
    private javax.swing.JToggleButton digital7;
    private javax.swing.JToggleButton digital8;
    private javax.swing.JToggleButton digital9;
    private javax.swing.JComboBox encoderSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labCompressor;
    private javax.swing.JLabel labStatus;
    private javax.swing.JLabel lcd1;
    private javax.swing.JLabel lcd2;
    private javax.swing.JLabel lcd3;
    private javax.swing.JLabel lcd4;
    private javax.swing.JLabel lcd5;
    private javax.swing.JLabel lcd6;
    private javax.swing.JProgressBar motor1;
    private javax.swing.JProgressBar motor10;
    private javax.swing.JProgressBar motor2;
    private javax.swing.JProgressBar motor3;
    private javax.swing.JProgressBar motor4;
    private javax.swing.JProgressBar motor5;
    private javax.swing.JProgressBar motor6;
    private javax.swing.JProgressBar motor7;
    private javax.swing.JProgressBar motor8;
    private javax.swing.JProgressBar motor9;
    private javax.swing.JRadioButton radAuto;
    private javax.swing.JRadioButton radTele;
    private javax.swing.JRadioButton radTest;
    private javax.swing.JSlider sliJoy1_1;
    private javax.swing.JSlider sliJoy1_2;
    private javax.swing.JSlider sliJoy1_3;
    private javax.swing.JSlider sliJoy1_4;
    private javax.swing.JSlider sliJoy1_5;
    private javax.swing.JSlider sliJoy1_6;
    private javax.swing.JSlider sliJoy2_1;
    private javax.swing.JSlider sliJoy2_2;
    private javax.swing.JSlider sliJoy2_3;
    private javax.swing.JSlider sliJoy2_4;
    private javax.swing.JSlider sliJoy2_5;
    private javax.swing.JSlider sliJoy2_6;
    private javax.swing.JSlider sliJoy3_1;
    private javax.swing.JSlider sliJoy3_2;
    private javax.swing.JSlider sliJoy3_3;
    private javax.swing.JSlider sliJoy3_4;
    private javax.swing.JSlider sliJoy3_5;
    private javax.swing.JSlider sliJoy3_6;
    private javax.swing.JSlider sliJoy4_1;
    private javax.swing.JSlider sliJoy4_2;
    private javax.swing.JSlider sliJoy4_3;
    private javax.swing.JSlider sliJoy4_4;
    private javax.swing.JSlider sliJoy4_5;
    private javax.swing.JSlider sliJoy4_6;
    private javax.swing.JLabel sol1;
    private javax.swing.JLabel sol2;
    private javax.swing.JLabel sol3;
    private javax.swing.JLabel sol4;
    private javax.swing.JLabel sol5;
    private javax.swing.JLabel sol6;
    private javax.swing.JLabel sol7;
    private javax.swing.JLabel sol8;
    // End of variables declaration//GEN-END:variables

    public CurrentState getOperatingState() {
        if (btnEnable.isSelected()) {
            if (radAuto.isSelected()) {
                return CurrentState.AUTONOMOUS;
            } else if (radTele.isSelected()) {
                return CurrentState.TELEOPERATED;
            } else if (radTest.isSelected()) {
                return CurrentState.TESTING;
            } else {
                Logger.severe("Invalid operating state!");
                return CurrentState.DISABLED;
            }
        } else {
            return CurrentState.DISABLED;
        }
    }

    public FloatOutput getJaguar(int id) {
        return getMotorColored(id, new Color(0xA10000), -1, 1);
    }

    public FloatOutput getVictor(int id) {
        return getMotorColored(id, new Color(0x008282), -1, 1);
    }

    public FloatOutput getTalon(int id) {
        return getMotorColored(id, new Color(0xA1A100), -1, 1);
    }

    public FloatOutput getServo(int id, float minInput, float maxInput) {
        return getMotorColored(id, new Color(0xFF0000), minInput, maxInput);
    }

    private FloatOutput getMotorColored(int id, final Color color, final float minInput, final float maxInput) {
        final JProgressBar jpb = motors[id - 1];
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jpb.setForeground(color);
            }
        });
        return new FloatOutput() {
            @Override
            public void writeValue(final float f) {
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        jpb.setValue(Math.round(((f - minInput) / (maxInput - minInput)) * (jpb.getMaximum() - jpb.getMinimum()) + jpb.getMinimum()));
                    }
                });
            }
        };
    }

    public BooleanOutput getSolenoid(int id) {
        final JLabel lab;
        switch (id) {
            case 1:
                lab = sol1;
                break;
            case 2:
                lab = sol2;
                break;
            case 3:
                lab = sol3;
                break;
            case 4:
                lab = sol4;
                break;
            case 5:
                lab = sol5;
                break;
            case 6:
                lab = sol6;
                break;
            case 7:
                lab = sol7;
                break;
            case 8:
                lab = sol8;
                break;
            default:
                throw new RuntimeException("Invalid solenoid ID: " + id);
        }
        BooleanOutput o = new BooleanOutput() {
            @Override
            public void writeValue(final boolean bln) {
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        lab.setForeground(bln ? ONCOLOR : Color.RED);
                    }
                });
            }
        };
        o.writeValue(false);
        return o;
    }
    public static final Color ONCOLOR = new Color(0, 192, 0);

    public FloatInputPoll getAnalog(int id) {
        final FloatInputPoll base = getAnalogValue(id);
        return new FloatInputPoll() {
            @Override
            public float readValue() { // Returns in the -3.5v to 3.5v range.
                return 7 * base.readValue() / 4095f - 3.5f;
            }
        };
    }

    public FloatInputPoll getAnalogValue(int id) {
        final JSlider sli;
        switch (id) {
            case 1:
                sli = analog1;
                break;
            case 2:
                sli = analog2;
                break;
            case 3:
                sli = analog3;
                break;
            case 4:
                sli = analog4;
                break;
            case 5:
                sli = analog5;
                break;
            case 6:
                sli = analog6;
                break;
            case 7:
                sli = analog7;
                break;
            case 8:
                sli = analog8;
                break;
            default:
                throw new RuntimeException("Invalid analog index: " + id);
        }
        return new FloatInputPoll() {
            @Override
            public float readValue() {
                return sli.getValue();
            }
        };
    }

    public BooleanInputPoll getDigital(int id) {
        final JToggleButton dig;
        switch (id) {
            case 1:
                dig = digital1;
                break;
            case 2:
                dig = digital2;
                break;
            case 3:
                dig = digital3;
                break;
            case 4:
                dig = digital4;
                break;
            case 5:
                dig = digital5;
                break;
            case 6:
                dig = digital6;
                break;
            case 7:
                dig = digital7;
                break;
            case 8:
                dig = digital8;
                break;
            case 9:
                dig = digital9;
                break;
            case 10:
                dig = digital10;
                break;
            case 11:
                dig = digital11;
                break;
            case 12:
                dig = digital12;
                break;
            case 13:
                dig = digital13;
                break;
            case 14:
                dig = digital14;
                break;
            default:
                throw new RuntimeException("Invalid digital input index: " + id);
        }
        return new BooleanInputPoll() {
            @Override
            public boolean readValue() {
                return dig.isSelected();
            }
        };
    }

    public void sendDSUpdate(final String value, int line) {
        final JLabel tgt;
        switch (line) {
            case 1:
                tgt = lcd1;
                break;
            case 2:
                tgt = lcd2;
                break;
            case 3:
                tgt = lcd3;
                break;
            case 4:
                tgt = lcd4;
                break;
            case 5:
                tgt = lcd5;
                break;
            case 6:
                tgt = lcd6;
                break;
            default:
                throw new RuntimeException("Bad LCD line: " + line);
        }
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                tgt.setText(value);
            }
        });
    }

    public FloatOutput getDSReadout(final String prefix, int line) {
        final JLabel tgt;
        switch (line) {
            case 1:
                tgt = lcd1;
                break;
            case 2:
                tgt = lcd2;
                break;
            case 3:
                tgt = lcd3;
                break;
            case 4:
                tgt = lcd4;
                break;
            case 5:
                tgt = lcd5;
                break;
            case 6:
                tgt = lcd6;
                break;
            default:
                throw new RuntimeException("Bad LCD line: " + line);
        }
        return new FloatOutput() {
            @Override
            public void writeValue(final float f) {
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        tgt.setText(prefix + ": " + f);
                    }
                });
            }
        };
    }

    public void setCompressor(boolean b) {
        labCompressor.setText(b ? "ENABLED" : "DISABLED");
    }
}
