package poultryinspector.interactor;

import ccre.chan.BooleanInput;
import ccre.chan.BooleanOutput;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

public class BooleanInputForm extends javax.swing.JFrame {

    public static void create(final String name, final BooleanInput bi) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BooleanInputForm(name, bi).setVisible(true);
            }
        });
    }

    private BooleanInputForm(String name, final BooleanInput binput) {
        initComponents();
        final BooleanOutput bo = new BooleanOutput() {
            @Override
            public void writeValue(final boolean b) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        labValue.setText(b ? "true" : "false");
                        labValue.setForeground(b ? new Color(0, 160, 0) : new Color(160, 0, 0));
                    }
                });
            }
        };
        binput.addTarget(bo);
        labValue.setText(binput.readValue() ? "true" : "false");
        // Purposefully not setting color. Color is a sign that the data has been updated and isn't the default.
        labName.setText(name);
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                binput.removeTarget(bo);
                setVisible(false);
                dispose();
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labName = new javax.swing.JLabel();
        labValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        labName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labName.setText("<NAME>");

        labValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labValue.setText("<VALUE>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(labValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labValue))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labValue;
    // End of variables declaration//GEN-END:variables
}
